### ISSUE TITLE
こんにちは質問がありました。

### ISSUE THREAD

**Issue by barkhaneum** [nyanpyou106/eye_controller_for_game_public#1]
こんにちは質問がありました。私はEyeTracker5を使って左目の位置と右目の位置を知りたいので購入しましたが、Stream Engineで実装できるかどうかを知りたいです。

**Comment by nyanpyou106** [comment]
こんにちはbarkhaneum。
[Stream EngineのAPI Reference](https://developer.tobii.com/product-integration/stream-engine/getting-started/#tobii_gaze_origin_subscribe)を見る限りでは、tobii_gaze_origin_subscribe関数を利用することで実装できそうです。
ですが私は試したことが無いので、確認は取れていません。

**Comment by barkhaneum** [comment]
そうなんですね。ありがとうございます。 あなたが投稿してくださったソースコードが私にとても役に立ったようです。 unityを通じて左目と右目のそれぞれの動きを知りたかったのですが、Tobieyetracker5は該当APIをサポートしていないようです。

**Comment by nyanpyou106** [comment]
> unityを通じて左目と右目のそれぞれの動きを知りたかったのですが、Tobieyetracker5は該当APIをサポートしていないようです。

そうでしたか…残念です。

**Comment by barkhaneum** [comment]
こんにちは。私は偶然あなたのソースコードをはがしながらEyeTracker5でもそれぞれの目に対する位置情報を受け取ることができることを確認しました。 本当にありがとうございます。 :)
